resources:
  jobs:
    sample_job:
      name: sample_job
      tasks:
        - task_key: bronze_task
          notebook_task:
            notebook_path: ../src/bronze_notebook.ipynb
        - task_key: silver_task
          depends_on:
            - task_key: bronze_task
          notebook_task:
            notebook_path: ../src/silver_notebook.ipynb
        - task_key: gold_task
          depends_on:
            - task_key: silver_task
          notebook_task:
            notebook_path: ../src/gold_notebook.ipynb